// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/org/type/employee.proto

package org

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmployeeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestType     string                 `protobuf:"bytes,1,opt,name=requestType,proto3" json:"requestType,omitempty"`
	Domain          string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	EmployeeId      string                 `protobuf:"bytes,3,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	Department      string                 `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
	Designation     string                 `protobuf:"bytes,5,opt,name=designation,proto3" json:"designation,omitempty"`
	Name            string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ProfileImageURL string                 `protobuf:"bytes,8,opt,name=profileImageURL,proto3" json:"profileImageURL,omitempty"`
	EmailId         string                 `protobuf:"bytes,9,opt,name=emailId,proto3" json:"emailId,omitempty"`
	Country         string                 `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	TimeZone        string                 `protobuf:"bytes,11,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EmployeeRequest) Reset() {
	*x = EmployeeRequest{}
	mi := &file_proto_org_type_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeRequest) ProtoMessage() {}

func (x *EmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_org_type_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeRequest.ProtoReflect.Descriptor instead.
func (*EmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_org_type_employee_proto_rawDescGZIP(), []int{0}
}

func (x *EmployeeRequest) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *EmployeeRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *EmployeeRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *EmployeeRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *EmployeeRequest) GetDesignation() string {
	if x != nil {
		return x.Designation
	}
	return ""
}

func (x *EmployeeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmployeeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EmployeeRequest) GetProfileImageURL() string {
	if x != nil {
		return x.ProfileImageURL
	}
	return ""
}

func (x *EmployeeRequest) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *EmployeeRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *EmployeeRequest) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

type EmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsError       bool                   `protobuf:"varint,1,opt,name=isError,proto3" json:"isError,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeResponse) Reset() {
	*x = EmployeeResponse{}
	mi := &file_proto_org_type_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeResponse) ProtoMessage() {}

func (x *EmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_org_type_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeResponse.ProtoReflect.Descriptor instead.
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_org_type_employee_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *EmployeeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_org_type_employee_proto protoreflect.FileDescriptor

const file_proto_org_type_employee_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/org/type/employee.proto\x12\x03org\"\xd3\x02\n" +
	"\x0fEmployeeRequest\x12 \n" +
	"\vrequestType\x18\x01 \x01(\tR\vrequestType\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1e\n" +
	"\n" +
	"employeeId\x18\x03 \x01(\tR\n" +
	"employeeId\x12\x1e\n" +
	"\n" +
	"department\x18\x04 \x01(\tR\n" +
	"department\x12 \n" +
	"\vdesignation\x18\x05 \x01(\tR\vdesignation\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12(\n" +
	"\x0fprofileImageURL\x18\b \x01(\tR\x0fprofileImageURL\x12\x18\n" +
	"\aemailId\x18\t \x01(\tR\aemailId\x12\x18\n" +
	"\acountry\x18\n" +
	" \x01(\tR\acountry\x12\x1a\n" +
	"\btimeZone\x18\v \x01(\tR\btimeZone\"F\n" +
	"\x10EmployeeResponse\x12\x18\n" +
	"\aisError\x18\x01 \x01(\bR\aisError\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x0eZ\fgenproto/orgb\x06proto3"

var (
	file_proto_org_type_employee_proto_rawDescOnce sync.Once
	file_proto_org_type_employee_proto_rawDescData []byte
)

func file_proto_org_type_employee_proto_rawDescGZIP() []byte {
	file_proto_org_type_employee_proto_rawDescOnce.Do(func() {
		file_proto_org_type_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_org_type_employee_proto_rawDesc), len(file_proto_org_type_employee_proto_rawDesc)))
	})
	return file_proto_org_type_employee_proto_rawDescData
}

var file_proto_org_type_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_org_type_employee_proto_goTypes = []any{
	(*EmployeeRequest)(nil),  // 0: org.EmployeeRequest
	(*EmployeeResponse)(nil), // 1: org.EmployeeResponse
}
var file_proto_org_type_employee_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_org_type_employee_proto_init() }
func file_proto_org_type_employee_proto_init() {
	if File_proto_org_type_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_org_type_employee_proto_rawDesc), len(file_proto_org_type_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_org_type_employee_proto_goTypes,
		DependencyIndexes: file_proto_org_type_employee_proto_depIdxs,
		MessageInfos:      file_proto_org_type_employee_proto_msgTypes,
	}.Build()
	File_proto_org_type_employee_proto = out.File
	file_proto_org_type_employee_proto_goTypes = nil
	file_proto_org_type_employee_proto_depIdxs = nil
}
