// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/org/org.proto

package org

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_org_org_proto protoreflect.FileDescriptor

const file_proto_org_org_proto_rawDesc = "" +
	"\n" +
	"\x13proto/org/org.proto\x12\x03org\x1a\x1dproto/org/type/employee.proto\x1a!proto/org/type/organization.proto\x1a#proto/org/type/org_attendance.proto\x1a\x1eproto/org/type/org_leave.proto\x1a#proto/org/type/dep_attendance.proto2\xc3\x03\n" +
	"\n" +
	"OrgService\x12?\n" +
	"\x10InitOrganization\x12\x13.org.InitOrgRequest\x1a\x14.org.InitOrgResponse\"\x00\x12<\n" +
	"\vOrgEmployee\x12\x14.org.EmployeeRequest\x1a\x15.org.EmployeeResponse\"\x00\x12O\n" +
	"\x14GetOrgAttendanceConf\x12\x19.org.OrgAttendanceRequest\x1a\x1a.org.OrgAttendanceResponse\"\x00\x12O\n" +
	"\x14GetDepAttendanceConf\x12\x19.org.DepAttendanceRequest\x1a\x1a.org.DepAttendanceResponse\"\x00\x12@\n" +
	"\x0fGetOrgLeaveConf\x12\x14.org.OrgLeaveRequest\x1a\x15.org.OrgLeaveResponse\"\x00\x12R\n" +
	"\x17DeductExpenseFromBudget\x12\x19.org.DeductExpenseRequest\x1a\x1a.org.DeductExpenseResponse\"\x00B\x0eZ\fgenproto/orgb\x06proto3"

var file_proto_org_org_proto_goTypes = []any{
	(*InitOrgRequest)(nil),        // 0: org.InitOrgRequest
	(*EmployeeRequest)(nil),       // 1: org.EmployeeRequest
	(*OrgAttendanceRequest)(nil),  // 2: org.OrgAttendanceRequest
	(*DepAttendanceRequest)(nil),  // 3: org.DepAttendanceRequest
	(*OrgLeaveRequest)(nil),       // 4: org.OrgLeaveRequest
	(*DeductExpenseRequest)(nil),  // 5: org.DeductExpenseRequest
	(*InitOrgResponse)(nil),       // 6: org.InitOrgResponse
	(*EmployeeResponse)(nil),      // 7: org.EmployeeResponse
	(*OrgAttendanceResponse)(nil), // 8: org.OrgAttendanceResponse
	(*DepAttendanceResponse)(nil), // 9: org.DepAttendanceResponse
	(*OrgLeaveResponse)(nil),      // 10: org.OrgLeaveResponse
	(*DeductExpenseResponse)(nil), // 11: org.DeductExpenseResponse
}
var file_proto_org_org_proto_depIdxs = []int32{
	0,  // 0: org.OrgService.InitOrganization:input_type -> org.InitOrgRequest
	1,  // 1: org.OrgService.OrgEmployee:input_type -> org.EmployeeRequest
	2,  // 2: org.OrgService.GetOrgAttendanceConf:input_type -> org.OrgAttendanceRequest
	3,  // 3: org.OrgService.GetDepAttendanceConf:input_type -> org.DepAttendanceRequest
	4,  // 4: org.OrgService.GetOrgLeaveConf:input_type -> org.OrgLeaveRequest
	5,  // 5: org.OrgService.DeductExpenseFromBudget:input_type -> org.DeductExpenseRequest
	6,  // 6: org.OrgService.InitOrganization:output_type -> org.InitOrgResponse
	7,  // 7: org.OrgService.OrgEmployee:output_type -> org.EmployeeResponse
	8,  // 8: org.OrgService.GetOrgAttendanceConf:output_type -> org.OrgAttendanceResponse
	9,  // 9: org.OrgService.GetDepAttendanceConf:output_type -> org.DepAttendanceResponse
	10, // 10: org.OrgService.GetOrgLeaveConf:output_type -> org.OrgLeaveResponse
	11, // 11: org.OrgService.DeductExpenseFromBudget:output_type -> org.DeductExpenseResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_org_org_proto_init() }
func file_proto_org_org_proto_init() {
	if File_proto_org_org_proto != nil {
		return
	}
	file_proto_org_type_employee_proto_init()
	file_proto_org_type_organization_proto_init()
	file_proto_org_type_org_attendance_proto_init()
	file_proto_org_type_org_leave_proto_init()
	file_proto_org_type_dep_attendance_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_org_org_proto_rawDesc), len(file_proto_org_org_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_org_org_proto_goTypes,
		DependencyIndexes: file_proto_org_org_proto_depIdxs,
	}.Build()
	File_proto_org_org_proto = out.File
	file_proto_org_org_proto_goTypes = nil
	file_proto_org_org_proto_depIdxs = nil
}
