// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/org/type/org_leave.proto

package org

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrgLeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgName       string                 `protobuf:"bytes,1,opt,name=orgName,proto3" json:"orgName,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgLeaveRequest) Reset() {
	*x = OrgLeaveRequest{}
	mi := &file_proto_org_type_org_leave_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgLeaveRequest) ProtoMessage() {}

func (x *OrgLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_org_type_org_leave_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgLeaveRequest.ProtoReflect.Descriptor instead.
func (*OrgLeaveRequest) Descriptor() ([]byte, []int) {
	return file_proto_org_type_org_leave_proto_rawDescGZIP(), []int{0}
}

func (x *OrgLeaveRequest) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *OrgLeaveRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *OrgLeaveRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type OrgLeaveConfiguration struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	OrgId                       string                 `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	OrgName                     string                 `protobuf:"bytes,2,opt,name=orgName,proto3" json:"orgName,omitempty"`
	Title                       string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	IsFixed                     bool                   `protobuf:"varint,4,opt,name=isFixed,proto3" json:"isFixed,omitempty"`
	Frequency                   string                 `protobuf:"bytes,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	LeaveCount                  float64                `protobuf:"fixed64,6,opt,name=leaveCount,proto3" json:"leaveCount,omitempty"`
	LeaveUnit                   string                 `protobuf:"bytes,7,opt,name=leaveUnit,proto3" json:"leaveUnit,omitempty"`
	MaxLeaveCount               float64                `protobuf:"fixed64,8,opt,name=maxLeaveCount,proto3" json:"maxLeaveCount,omitempty"`
	IsCarryForwardAllowed       bool                   `protobuf:"varint,9,opt,name=isCarryForwardAllowed,proto3" json:"isCarryForwardAllowed,omitempty"`
	MaxCarryForwardCount        float64                `protobuf:"fixed64,10,opt,name=maxCarryForwardCount,proto3" json:"maxCarryForwardCount,omitempty"`
	BulkLeaveCount              int32                  `protobuf:"varint,11,opt,name=bulkLeaveCount,proto3" json:"bulkLeaveCount,omitempty"`
	BulkLeaveNoticeInDays       int32                  `protobuf:"varint,12,opt,name=bulkLeaveNoticeInDays,proto3" json:"bulkLeaveNoticeInDays,omitempty"`
	IsEncashmentAllowed         bool                   `protobuf:"varint,13,opt,name=isEncashmentAllowed,proto3" json:"isEncashmentAllowed,omitempty"`
	ApplicableAfterWorkingDays  int32                  `protobuf:"varint,14,opt,name=applicableAfterWorkingDays,proto3" json:"applicableAfterWorkingDays,omitempty"`
	DocumentRequired            bool                   `protobuf:"varint,15,opt,name=documentRequired,proto3" json:"documentRequired,omitempty"`
	WeeklyOffAndHolidayIncluded bool                   `protobuf:"varint,16,opt,name=weeklyOffAndHolidayIncluded,proto3" json:"weeklyOffAndHolidayIncluded,omitempty"`
	IsActive                    bool                   `protobuf:"varint,17,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Description                 string                 `protobuf:"bytes,18,opt,name=description,proto3" json:"description,omitempty"`
	YearStartDate               string                 `protobuf:"bytes,19,opt,name=yearStartDate,proto3" json:"yearStartDate,omitempty"`
	YearEndDate                 string                 `protobuf:"bytes,20,opt,name=yearEndDate,proto3" json:"yearEndDate,omitempty"`
	IncludeWeeklyOffDays        bool                   `protobuf:"varint,21,opt,name=IncludeWeeklyOffDays,proto3" json:"IncludeWeeklyOffDays,omitempty"`
	IncludeHolidays             bool                   `protobuf:"varint,22,opt,name=IncludeHolidays,proto3" json:"IncludeHolidays,omitempty"`
	MaxLeaveAllowedCount        float64                `protobuf:"fixed64,23,opt,name=MaxLeaveAllowedCount,proto3" json:"MaxLeaveAllowedCount,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *OrgLeaveConfiguration) Reset() {
	*x = OrgLeaveConfiguration{}
	mi := &file_proto_org_type_org_leave_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgLeaveConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgLeaveConfiguration) ProtoMessage() {}

func (x *OrgLeaveConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_org_type_org_leave_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgLeaveConfiguration.ProtoReflect.Descriptor instead.
func (*OrgLeaveConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_org_type_org_leave_proto_rawDescGZIP(), []int{1}
}

func (x *OrgLeaveConfiguration) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *OrgLeaveConfiguration) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *OrgLeaveConfiguration) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OrgLeaveConfiguration) GetIsFixed() bool {
	if x != nil {
		return x.IsFixed
	}
	return false
}

func (x *OrgLeaveConfiguration) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *OrgLeaveConfiguration) GetLeaveCount() float64 {
	if x != nil {
		return x.LeaveCount
	}
	return 0
}

func (x *OrgLeaveConfiguration) GetLeaveUnit() string {
	if x != nil {
		return x.LeaveUnit
	}
	return ""
}

func (x *OrgLeaveConfiguration) GetMaxLeaveCount() float64 {
	if x != nil {
		return x.MaxLeaveCount
	}
	return 0
}

func (x *OrgLeaveConfiguration) GetIsCarryForwardAllowed() bool {
	if x != nil {
		return x.IsCarryForwardAllowed
	}
	return false
}

func (x *OrgLeaveConfiguration) GetMaxCarryForwardCount() float64 {
	if x != nil {
		return x.MaxCarryForwardCount
	}
	return 0
}

func (x *OrgLeaveConfiguration) GetBulkLeaveCount() int32 {
	if x != nil {
		return x.BulkLeaveCount
	}
	return 0
}

func (x *OrgLeaveConfiguration) GetBulkLeaveNoticeInDays() int32 {
	if x != nil {
		return x.BulkLeaveNoticeInDays
	}
	return 0
}

func (x *OrgLeaveConfiguration) GetIsEncashmentAllowed() bool {
	if x != nil {
		return x.IsEncashmentAllowed
	}
	return false
}

func (x *OrgLeaveConfiguration) GetApplicableAfterWorkingDays() int32 {
	if x != nil {
		return x.ApplicableAfterWorkingDays
	}
	return 0
}

func (x *OrgLeaveConfiguration) GetDocumentRequired() bool {
	if x != nil {
		return x.DocumentRequired
	}
	return false
}

func (x *OrgLeaveConfiguration) GetWeeklyOffAndHolidayIncluded() bool {
	if x != nil {
		return x.WeeklyOffAndHolidayIncluded
	}
	return false
}

func (x *OrgLeaveConfiguration) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *OrgLeaveConfiguration) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrgLeaveConfiguration) GetYearStartDate() string {
	if x != nil {
		return x.YearStartDate
	}
	return ""
}

func (x *OrgLeaveConfiguration) GetYearEndDate() string {
	if x != nil {
		return x.YearEndDate
	}
	return ""
}

func (x *OrgLeaveConfiguration) GetIncludeWeeklyOffDays() bool {
	if x != nil {
		return x.IncludeWeeklyOffDays
	}
	return false
}

func (x *OrgLeaveConfiguration) GetIncludeHolidays() bool {
	if x != nil {
		return x.IncludeHolidays
	}
	return false
}

func (x *OrgLeaveConfiguration) GetMaxLeaveAllowedCount() float64 {
	if x != nil {
		return x.MaxLeaveAllowedCount
	}
	return 0
}

type OrgLeaveResponse struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	OrgName                string                   `protobuf:"bytes,1,opt,name=orgName,proto3" json:"orgName,omitempty"`
	OrgLeaveConfigurations []*OrgLeaveConfiguration `protobuf:"bytes,2,rep,name=orgLeaveConfigurations,proto3" json:"orgLeaveConfigurations,omitempty"`
	Country                string                   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OrgLeaveResponse) Reset() {
	*x = OrgLeaveResponse{}
	mi := &file_proto_org_type_org_leave_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgLeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgLeaveResponse) ProtoMessage() {}

func (x *OrgLeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_org_type_org_leave_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgLeaveResponse.ProtoReflect.Descriptor instead.
func (*OrgLeaveResponse) Descriptor() ([]byte, []int) {
	return file_proto_org_type_org_leave_proto_rawDescGZIP(), []int{2}
}

func (x *OrgLeaveResponse) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *OrgLeaveResponse) GetOrgLeaveConfigurations() []*OrgLeaveConfiguration {
	if x != nil {
		return x.OrgLeaveConfigurations
	}
	return nil
}

func (x *OrgLeaveResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_proto_org_type_org_leave_proto protoreflect.FileDescriptor

const file_proto_org_type_org_leave_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/org/type/org_leave.proto\x12\x03org\"]\n" +
	"\x0fOrgLeaveRequest\x12\x18\n" +
	"\aorgName\x18\x01 \x01(\tR\aorgName\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\"\xb9\a\n" +
	"\x15OrgLeaveConfiguration\x12\x14\n" +
	"\x05orgId\x18\x01 \x01(\tR\x05orgId\x12\x18\n" +
	"\aorgName\x18\x02 \x01(\tR\aorgName\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\aisFixed\x18\x04 \x01(\bR\aisFixed\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\tR\tfrequency\x12\x1e\n" +
	"\n" +
	"leaveCount\x18\x06 \x01(\x01R\n" +
	"leaveCount\x12\x1c\n" +
	"\tleaveUnit\x18\a \x01(\tR\tleaveUnit\x12$\n" +
	"\rmaxLeaveCount\x18\b \x01(\x01R\rmaxLeaveCount\x124\n" +
	"\x15isCarryForwardAllowed\x18\t \x01(\bR\x15isCarryForwardAllowed\x122\n" +
	"\x14maxCarryForwardCount\x18\n" +
	" \x01(\x01R\x14maxCarryForwardCount\x12&\n" +
	"\x0ebulkLeaveCount\x18\v \x01(\x05R\x0ebulkLeaveCount\x124\n" +
	"\x15bulkLeaveNoticeInDays\x18\f \x01(\x05R\x15bulkLeaveNoticeInDays\x120\n" +
	"\x13isEncashmentAllowed\x18\r \x01(\bR\x13isEncashmentAllowed\x12>\n" +
	"\x1aapplicableAfterWorkingDays\x18\x0e \x01(\x05R\x1aapplicableAfterWorkingDays\x12*\n" +
	"\x10documentRequired\x18\x0f \x01(\bR\x10documentRequired\x12@\n" +
	"\x1bweeklyOffAndHolidayIncluded\x18\x10 \x01(\bR\x1bweeklyOffAndHolidayIncluded\x12\x1a\n" +
	"\bisActive\x18\x11 \x01(\bR\bisActive\x12 \n" +
	"\vdescription\x18\x12 \x01(\tR\vdescription\x12$\n" +
	"\ryearStartDate\x18\x13 \x01(\tR\ryearStartDate\x12 \n" +
	"\vyearEndDate\x18\x14 \x01(\tR\vyearEndDate\x122\n" +
	"\x14IncludeWeeklyOffDays\x18\x15 \x01(\bR\x14IncludeWeeklyOffDays\x12(\n" +
	"\x0fIncludeHolidays\x18\x16 \x01(\bR\x0fIncludeHolidays\x122\n" +
	"\x14MaxLeaveAllowedCount\x18\x17 \x01(\x01R\x14MaxLeaveAllowedCount\"\x9a\x01\n" +
	"\x10OrgLeaveResponse\x12\x18\n" +
	"\aorgName\x18\x01 \x01(\tR\aorgName\x12R\n" +
	"\x16orgLeaveConfigurations\x18\x02 \x03(\v2\x1a.org.OrgLeaveConfigurationR\x16orgLeaveConfigurations\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountryB\x0eZ\fgenproto/orgb\x06proto3"

var (
	file_proto_org_type_org_leave_proto_rawDescOnce sync.Once
	file_proto_org_type_org_leave_proto_rawDescData []byte
)

func file_proto_org_type_org_leave_proto_rawDescGZIP() []byte {
	file_proto_org_type_org_leave_proto_rawDescOnce.Do(func() {
		file_proto_org_type_org_leave_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_org_type_org_leave_proto_rawDesc), len(file_proto_org_type_org_leave_proto_rawDesc)))
	})
	return file_proto_org_type_org_leave_proto_rawDescData
}

var file_proto_org_type_org_leave_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_org_type_org_leave_proto_goTypes = []any{
	(*OrgLeaveRequest)(nil),       // 0: org.OrgLeaveRequest
	(*OrgLeaveConfiguration)(nil), // 1: org.OrgLeaveConfiguration
	(*OrgLeaveResponse)(nil),      // 2: org.OrgLeaveResponse
}
var file_proto_org_type_org_leave_proto_depIdxs = []int32{
	1, // 0: org.OrgLeaveResponse.orgLeaveConfigurations:type_name -> org.OrgLeaveConfiguration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_org_type_org_leave_proto_init() }
func file_proto_org_type_org_leave_proto_init() {
	if File_proto_org_type_org_leave_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_org_type_org_leave_proto_rawDesc), len(file_proto_org_type_org_leave_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_org_type_org_leave_proto_goTypes,
		DependencyIndexes: file_proto_org_type_org_leave_proto_depIdxs,
		MessageInfos:      file_proto_org_type_org_leave_proto_msgTypes,
	}.Build()
	File_proto_org_type_org_leave_proto = out.File
	file_proto_org_type_org_leave_proto_goTypes = nil
	file_proto_org_type_org_leave_proto_depIdxs = nil
}
