// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/org/type/org_attendance.proto

package org

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrgAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgName       string                 `protobuf:"bytes,1,opt,name=orgName,proto3" json:"orgName,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgAttendanceRequest) Reset() {
	*x = OrgAttendanceRequest{}
	mi := &file_proto_org_type_org_attendance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgAttendanceRequest) ProtoMessage() {}

func (x *OrgAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_org_type_org_attendance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgAttendanceRequest.ProtoReflect.Descriptor instead.
func (*OrgAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_org_type_org_attendance_proto_rawDescGZIP(), []int{0}
}

func (x *OrgAttendanceRequest) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *OrgAttendanceRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *OrgAttendanceRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type OrgAttendanceResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	OrgId                   string                 `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	OrgName                 string                 `protobuf:"bytes,2,opt,name=orgName,proto3" json:"orgName,omitempty"`
	CaptureCheckInLocation  bool                   `protobuf:"varint,3,opt,name=captureCheckInLocation,proto3" json:"captureCheckInLocation,omitempty"`
	EnforceLocationCheckIn  bool                   `protobuf:"varint,4,opt,name=enforceLocationCheckIn,proto3" json:"enforceLocationCheckIn,omitempty"`
	EnforceLocationCheckOut bool                   `protobuf:"varint,5,opt,name=enforceLocationCheckOut,proto3" json:"enforceLocationCheckOut,omitempty"`
	RequiredLat             float64                `protobuf:"fixed64,6,opt,name=requiredLat,proto3" json:"requiredLat,omitempty"`
	RequiredLng             float64                `protobuf:"fixed64,7,opt,name=requiredLng,proto3" json:"requiredLng,omitempty"`
	FlexiHoursEnabled       bool                   `protobuf:"varint,8,opt,name=flexiHoursEnabled,proto3" json:"flexiHoursEnabled,omitempty"`
	FlexiHourWindowInMin    int32                  `protobuf:"varint,9,opt,name=flexiHourWindowInMin,proto3" json:"flexiHourWindowInMin,omitempty"`
	OrgCheckInTime          string                 `protobuf:"bytes,10,opt,name=orgCheckInTime,proto3" json:"orgCheckInTime,omitempty"`
	OrgCheckOutTime         string                 `protobuf:"bytes,11,opt,name=orgCheckOutTime,proto3" json:"orgCheckOutTime,omitempty"`
	CheckInMarginInMin      int32                  `protobuf:"varint,12,opt,name=checkInMarginInMin,proto3" json:"checkInMarginInMin,omitempty"`
	DailyWorkingHours       float32                `protobuf:"fixed32,13,opt,name=dailyWorkingHours,proto3" json:"dailyWorkingHours,omitempty"`
	WorkingDaysPerWeek      float32                `protobuf:"fixed32,14,opt,name=workingDaysPerWeek,proto3" json:"workingDaysPerWeek,omitempty"`
	Country                 string                 `protobuf:"bytes,15,opt,name=country,proto3" json:"country,omitempty"`
	WeeklyOffDays           []string               `protobuf:"bytes,16,rep,name=weeklyOffDays,proto3" json:"weeklyOffDays,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OrgAttendanceResponse) Reset() {
	*x = OrgAttendanceResponse{}
	mi := &file_proto_org_type_org_attendance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgAttendanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgAttendanceResponse) ProtoMessage() {}

func (x *OrgAttendanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_org_type_org_attendance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgAttendanceResponse.ProtoReflect.Descriptor instead.
func (*OrgAttendanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_org_type_org_attendance_proto_rawDescGZIP(), []int{1}
}

func (x *OrgAttendanceResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *OrgAttendanceResponse) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *OrgAttendanceResponse) GetCaptureCheckInLocation() bool {
	if x != nil {
		return x.CaptureCheckInLocation
	}
	return false
}

func (x *OrgAttendanceResponse) GetEnforceLocationCheckIn() bool {
	if x != nil {
		return x.EnforceLocationCheckIn
	}
	return false
}

func (x *OrgAttendanceResponse) GetEnforceLocationCheckOut() bool {
	if x != nil {
		return x.EnforceLocationCheckOut
	}
	return false
}

func (x *OrgAttendanceResponse) GetRequiredLat() float64 {
	if x != nil {
		return x.RequiredLat
	}
	return 0
}

func (x *OrgAttendanceResponse) GetRequiredLng() float64 {
	if x != nil {
		return x.RequiredLng
	}
	return 0
}

func (x *OrgAttendanceResponse) GetFlexiHoursEnabled() bool {
	if x != nil {
		return x.FlexiHoursEnabled
	}
	return false
}

func (x *OrgAttendanceResponse) GetFlexiHourWindowInMin() int32 {
	if x != nil {
		return x.FlexiHourWindowInMin
	}
	return 0
}

func (x *OrgAttendanceResponse) GetOrgCheckInTime() string {
	if x != nil {
		return x.OrgCheckInTime
	}
	return ""
}

func (x *OrgAttendanceResponse) GetOrgCheckOutTime() string {
	if x != nil {
		return x.OrgCheckOutTime
	}
	return ""
}

func (x *OrgAttendanceResponse) GetCheckInMarginInMin() int32 {
	if x != nil {
		return x.CheckInMarginInMin
	}
	return 0
}

func (x *OrgAttendanceResponse) GetDailyWorkingHours() float32 {
	if x != nil {
		return x.DailyWorkingHours
	}
	return 0
}

func (x *OrgAttendanceResponse) GetWorkingDaysPerWeek() float32 {
	if x != nil {
		return x.WorkingDaysPerWeek
	}
	return 0
}

func (x *OrgAttendanceResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *OrgAttendanceResponse) GetWeeklyOffDays() []string {
	if x != nil {
		return x.WeeklyOffDays
	}
	return nil
}

var File_proto_org_type_org_attendance_proto protoreflect.FileDescriptor

const file_proto_org_type_org_attendance_proto_rawDesc = "" +
	"\n" +
	"#proto/org/type/org_attendance.proto\x12\x03org\"b\n" +
	"\x14OrgAttendanceRequest\x12\x18\n" +
	"\aorgName\x18\x01 \x01(\tR\aorgName\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\"\xb7\x05\n" +
	"\x15OrgAttendanceResponse\x12\x14\n" +
	"\x05orgId\x18\x01 \x01(\tR\x05orgId\x12\x18\n" +
	"\aorgName\x18\x02 \x01(\tR\aorgName\x126\n" +
	"\x16captureCheckInLocation\x18\x03 \x01(\bR\x16captureCheckInLocation\x126\n" +
	"\x16enforceLocationCheckIn\x18\x04 \x01(\bR\x16enforceLocationCheckIn\x128\n" +
	"\x17enforceLocationCheckOut\x18\x05 \x01(\bR\x17enforceLocationCheckOut\x12 \n" +
	"\vrequiredLat\x18\x06 \x01(\x01R\vrequiredLat\x12 \n" +
	"\vrequiredLng\x18\a \x01(\x01R\vrequiredLng\x12,\n" +
	"\x11flexiHoursEnabled\x18\b \x01(\bR\x11flexiHoursEnabled\x122\n" +
	"\x14flexiHourWindowInMin\x18\t \x01(\x05R\x14flexiHourWindowInMin\x12&\n" +
	"\x0eorgCheckInTime\x18\n" +
	" \x01(\tR\x0eorgCheckInTime\x12(\n" +
	"\x0forgCheckOutTime\x18\v \x01(\tR\x0forgCheckOutTime\x12.\n" +
	"\x12checkInMarginInMin\x18\f \x01(\x05R\x12checkInMarginInMin\x12,\n" +
	"\x11dailyWorkingHours\x18\r \x01(\x02R\x11dailyWorkingHours\x12.\n" +
	"\x12workingDaysPerWeek\x18\x0e \x01(\x02R\x12workingDaysPerWeek\x12\x18\n" +
	"\acountry\x18\x0f \x01(\tR\acountry\x12$\n" +
	"\rweeklyOffDays\x18\x10 \x03(\tR\rweeklyOffDaysB\x0eZ\fgenproto/orgb\x06proto3"

var (
	file_proto_org_type_org_attendance_proto_rawDescOnce sync.Once
	file_proto_org_type_org_attendance_proto_rawDescData []byte
)

func file_proto_org_type_org_attendance_proto_rawDescGZIP() []byte {
	file_proto_org_type_org_attendance_proto_rawDescOnce.Do(func() {
		file_proto_org_type_org_attendance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_org_type_org_attendance_proto_rawDesc), len(file_proto_org_type_org_attendance_proto_rawDesc)))
	})
	return file_proto_org_type_org_attendance_proto_rawDescData
}

var file_proto_org_type_org_attendance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_org_type_org_attendance_proto_goTypes = []any{
	(*OrgAttendanceRequest)(nil),  // 0: org.OrgAttendanceRequest
	(*OrgAttendanceResponse)(nil), // 1: org.OrgAttendanceResponse
}
var file_proto_org_type_org_attendance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_org_type_org_attendance_proto_init() }
func file_proto_org_type_org_attendance_proto_init() {
	if File_proto_org_type_org_attendance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_org_type_org_attendance_proto_rawDesc), len(file_proto_org_type_org_attendance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_org_type_org_attendance_proto_goTypes,
		DependencyIndexes: file_proto_org_type_org_attendance_proto_depIdxs,
		MessageInfos:      file_proto_org_type_org_attendance_proto_msgTypes,
	}.Build()
	File_proto_org_type_org_attendance_proto = out.File
	file_proto_org_type_org_attendance_proto_goTypes = nil
	file_proto_org_type_org_attendance_proto_depIdxs = nil
}
