// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/org/type/organization.proto

package org

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitOrgRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Eid               string                 `protobuf:"bytes,2,opt,name=eid,proto3" json:"eid,omitempty"`
	Domain            string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	OrgName           string                 `protobuf:"bytes,4,opt,name=orgName,proto3" json:"orgName,omitempty"`
	AdminEmailId      string                 `protobuf:"bytes,5,opt,name=adminEmailId,proto3" json:"adminEmailId,omitempty"`
	AdminPhoneNumber  string                 `protobuf:"bytes,6,opt,name=adminPhoneNumber,proto3" json:"adminPhoneNumber,omitempty"`
	AdminName         string                 `protobuf:"bytes,7,opt,name=adminName,proto3" json:"adminName,omitempty"`
	Department        string                 `protobuf:"bytes,8,opt,name=department,proto3" json:"department,omitempty"`
	Designation       string                 `protobuf:"bytes,9,opt,name=designation,proto3" json:"designation,omitempty"`
	EmailVerified     bool                   `protobuf:"varint,10,opt,name=emailVerified,proto3" json:"emailVerified,omitempty"`
	Password          string                 `protobuf:"bytes,11,opt,name=password,proto3" json:"password,omitempty"`
	Role              string                 `protobuf:"bytes,12,opt,name=role,proto3" json:"role,omitempty"`
	FirstLoginPending bool                   `protobuf:"varint,13,opt,name=firstLoginPending,proto3" json:"firstLoginPending,omitempty"`
	Status            string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	UseGoogleOAuth    bool                   `protobuf:"varint,15,opt,name=useGoogleOAuth,proto3" json:"useGoogleOAuth,omitempty"`
	Country           string                 `protobuf:"bytes,16,opt,name=country,proto3" json:"country,omitempty"`
	TimeZone          string                 `protobuf:"bytes,17,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitOrgRequest) Reset() {
	*x = InitOrgRequest{}
	mi := &file_proto_org_type_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitOrgRequest) ProtoMessage() {}

func (x *InitOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_org_type_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitOrgRequest.ProtoReflect.Descriptor instead.
func (*InitOrgRequest) Descriptor() ([]byte, []int) {
	return file_proto_org_type_organization_proto_rawDescGZIP(), []int{0}
}

func (x *InitOrgRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InitOrgRequest) GetEid() string {
	if x != nil {
		return x.Eid
	}
	return ""
}

func (x *InitOrgRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *InitOrgRequest) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *InitOrgRequest) GetAdminEmailId() string {
	if x != nil {
		return x.AdminEmailId
	}
	return ""
}

func (x *InitOrgRequest) GetAdminPhoneNumber() string {
	if x != nil {
		return x.AdminPhoneNumber
	}
	return ""
}

func (x *InitOrgRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *InitOrgRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *InitOrgRequest) GetDesignation() string {
	if x != nil {
		return x.Designation
	}
	return ""
}

func (x *InitOrgRequest) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *InitOrgRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *InitOrgRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *InitOrgRequest) GetFirstLoginPending() bool {
	if x != nil {
		return x.FirstLoginPending
	}
	return false
}

func (x *InitOrgRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InitOrgRequest) GetUseGoogleOAuth() bool {
	if x != nil {
		return x.UseGoogleOAuth
	}
	return false
}

func (x *InitOrgRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *InitOrgRequest) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

type InitOrgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsError       bool                   `protobuf:"varint,1,opt,name=isError,proto3" json:"isError,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitOrgResponse) Reset() {
	*x = InitOrgResponse{}
	mi := &file_proto_org_type_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitOrgResponse) ProtoMessage() {}

func (x *InitOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_org_type_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitOrgResponse.ProtoReflect.Descriptor instead.
func (*InitOrgResponse) Descriptor() ([]byte, []int) {
	return file_proto_org_type_organization_proto_rawDescGZIP(), []int{1}
}

func (x *InitOrgResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *InitOrgResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeductExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,2,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	FiscalYear    string                 `protobuf:"bytes,3,opt,name=fiscalYear,proto3" json:"fiscalYear,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	ExpenseId     string                 `protobuf:"bytes,6,opt,name=expenseId,proto3" json:"expenseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductExpenseRequest) Reset() {
	*x = DeductExpenseRequest{}
	mi := &file_proto_org_type_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductExpenseRequest) ProtoMessage() {}

func (x *DeductExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_org_type_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductExpenseRequest.ProtoReflect.Descriptor instead.
func (*DeductExpenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_org_type_organization_proto_rawDescGZIP(), []int{2}
}

func (x *DeductExpenseRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DeductExpenseRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *DeductExpenseRequest) GetFiscalYear() string {
	if x != nil {
		return x.FiscalYear
	}
	return ""
}

func (x *DeductExpenseRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DeductExpenseRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DeductExpenseRequest) GetExpenseId() string {
	if x != nil {
		return x.ExpenseId
	}
	return ""
}

type DeductExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsError       bool                   `protobuf:"varint,1,opt,name=isError,proto3" json:"isError,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductExpenseResponse) Reset() {
	*x = DeductExpenseResponse{}
	mi := &file_proto_org_type_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductExpenseResponse) ProtoMessage() {}

func (x *DeductExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_org_type_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductExpenseResponse.ProtoReflect.Descriptor instead.
func (*DeductExpenseResponse) Descriptor() ([]byte, []int) {
	return file_proto_org_type_organization_proto_rawDescGZIP(), []int{3}
}

func (x *DeductExpenseResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *DeductExpenseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_org_type_organization_proto protoreflect.FileDescriptor

const file_proto_org_type_organization_proto_rawDesc = "" +
	"\n" +
	"!proto/org/type/organization.proto\x12\x03org\"\x8e\x04\n" +
	"\x0eInitOrgRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03eid\x18\x02 \x01(\tR\x03eid\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x18\n" +
	"\aorgName\x18\x04 \x01(\tR\aorgName\x12\"\n" +
	"\fadminEmailId\x18\x05 \x01(\tR\fadminEmailId\x12*\n" +
	"\x10adminPhoneNumber\x18\x06 \x01(\tR\x10adminPhoneNumber\x12\x1c\n" +
	"\tadminName\x18\a \x01(\tR\tadminName\x12\x1e\n" +
	"\n" +
	"department\x18\b \x01(\tR\n" +
	"department\x12 \n" +
	"\vdesignation\x18\t \x01(\tR\vdesignation\x12$\n" +
	"\remailVerified\x18\n" +
	" \x01(\bR\remailVerified\x12\x1a\n" +
	"\bpassword\x18\v \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\f \x01(\tR\x04role\x12,\n" +
	"\x11firstLoginPending\x18\r \x01(\bR\x11firstLoginPending\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12&\n" +
	"\x0euseGoogleOAuth\x18\x0f \x01(\bR\x0euseGoogleOAuth\x12\x18\n" +
	"\acountry\x18\x10 \x01(\tR\acountry\x12\x1a\n" +
	"\btimeZone\x18\x11 \x01(\tR\btimeZone\"E\n" +
	"\x0fInitOrgResponse\x12\x18\n" +
	"\aisError\x18\x01 \x01(\bR\aisError\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc4\x01\n" +
	"\x14DeductExpenseRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\"\n" +
	"\fdepartmentId\x18\x02 \x01(\tR\fdepartmentId\x12\x1e\n" +
	"\n" +
	"fiscalYear\x18\x03 \x01(\tR\n" +
	"fiscalYear\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1c\n" +
	"\texpenseId\x18\x06 \x01(\tR\texpenseId\"K\n" +
	"\x15DeductExpenseResponse\x12\x18\n" +
	"\aisError\x18\x01 \x01(\bR\aisError\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x0eZ\fgenproto/orgb\x06proto3"

var (
	file_proto_org_type_organization_proto_rawDescOnce sync.Once
	file_proto_org_type_organization_proto_rawDescData []byte
)

func file_proto_org_type_organization_proto_rawDescGZIP() []byte {
	file_proto_org_type_organization_proto_rawDescOnce.Do(func() {
		file_proto_org_type_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_org_type_organization_proto_rawDesc), len(file_proto_org_type_organization_proto_rawDesc)))
	})
	return file_proto_org_type_organization_proto_rawDescData
}

var file_proto_org_type_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_org_type_organization_proto_goTypes = []any{
	(*InitOrgRequest)(nil),        // 0: org.InitOrgRequest
	(*InitOrgResponse)(nil),       // 1: org.InitOrgResponse
	(*DeductExpenseRequest)(nil),  // 2: org.DeductExpenseRequest
	(*DeductExpenseResponse)(nil), // 3: org.DeductExpenseResponse
}
var file_proto_org_type_organization_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_org_type_organization_proto_init() }
func file_proto_org_type_organization_proto_init() {
	if File_proto_org_type_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_org_type_organization_proto_rawDesc), len(file_proto_org_type_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_org_type_organization_proto_goTypes,
		DependencyIndexes: file_proto_org_type_organization_proto_depIdxs,
		MessageInfos:      file_proto_org_type_organization_proto_msgTypes,
	}.Build()
	File_proto_org_type_organization_proto = out.File
	file_proto_org_type_organization_proto_goTypes = nil
	file_proto_org_type_organization_proto_depIdxs = nil
}
