// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/monitor/monitor.proto

package monitor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_monitor_monitor_proto protoreflect.FileDescriptor

const file_proto_monitor_monitor_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/monitor/monitor.proto\x12\amonitor\x1a:proto/monitor/type/update_employee_attendance_status.proto2\x84\x01\n" +
	"\x0eMonitorService\x12r\n" +
	"\x1bUpdateCheckInCheckoutStatus\x12'.monitor.EmployeeCheckInCheckOutRequest\x1a(.monitor.EmployeeCheckInCheckOutResponse\"\x00B\x12Z\x10genproto/monitorb\x06proto3"

var file_proto_monitor_monitor_proto_goTypes = []any{
	(*EmployeeCheckInCheckOutRequest)(nil),  // 0: monitor.EmployeeCheckInCheckOutRequest
	(*EmployeeCheckInCheckOutResponse)(nil), // 1: monitor.EmployeeCheckInCheckOutResponse
}
var file_proto_monitor_monitor_proto_depIdxs = []int32{
	0, // 0: monitor.MonitorService.UpdateCheckInCheckoutStatus:input_type -> monitor.EmployeeCheckInCheckOutRequest
	1, // 1: monitor.MonitorService.UpdateCheckInCheckoutStatus:output_type -> monitor.EmployeeCheckInCheckOutResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_monitor_monitor_proto_init() }
func file_proto_monitor_monitor_proto_init() {
	if File_proto_monitor_monitor_proto != nil {
		return
	}
	file_proto_monitor_type_update_employee_attendance_status_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_monitor_monitor_proto_rawDesc), len(file_proto_monitor_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_monitor_monitor_proto_goTypes,
		DependencyIndexes: file_proto_monitor_monitor_proto_depIdxs,
	}.Build()
	File_proto_monitor_monitor_proto = out.File
	file_proto_monitor_monitor_proto_goTypes = nil
	file_proto_monitor_monitor_proto_depIdxs = nil
}
