// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/monitor/type/update_employee_attendance_status.proto

package monitor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmployeeCheckInCheckOutRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Day               int32                  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Month             int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Year              int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	EmployeeId        string                 `protobuf:"bytes,4,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	IsCheckedIn       bool                   `protobuf:"varint,5,opt,name=isCheckedIn,proto3" json:"isCheckedIn,omitempty"`
	CheckInTimestamp  string                 `protobuf:"bytes,6,opt,name=checkInTimestamp,proto3" json:"checkInTimestamp,omitempty"`
	IsCheckedOut      bool                   `protobuf:"varint,7,opt,name=isCheckedOut,proto3" json:"isCheckedOut,omitempty"`
	CheckOutTimestamp string                 `protobuf:"bytes,8,opt,name=checkOutTimestamp,proto3" json:"checkOutTimestamp,omitempty"`
	Domain            string                 `protobuf:"bytes,9,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EmployeeCheckInCheckOutRequest) Reset() {
	*x = EmployeeCheckInCheckOutRequest{}
	mi := &file_proto_monitor_type_update_employee_attendance_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeCheckInCheckOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeCheckInCheckOutRequest) ProtoMessage() {}

func (x *EmployeeCheckInCheckOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_type_update_employee_attendance_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeCheckInCheckOutRequest.ProtoReflect.Descriptor instead.
func (*EmployeeCheckInCheckOutRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_type_update_employee_attendance_status_proto_rawDescGZIP(), []int{0}
}

func (x *EmployeeCheckInCheckOutRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *EmployeeCheckInCheckOutRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *EmployeeCheckInCheckOutRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *EmployeeCheckInCheckOutRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *EmployeeCheckInCheckOutRequest) GetIsCheckedIn() bool {
	if x != nil {
		return x.IsCheckedIn
	}
	return false
}

func (x *EmployeeCheckInCheckOutRequest) GetCheckInTimestamp() string {
	if x != nil {
		return x.CheckInTimestamp
	}
	return ""
}

func (x *EmployeeCheckInCheckOutRequest) GetIsCheckedOut() bool {
	if x != nil {
		return x.IsCheckedOut
	}
	return false
}

func (x *EmployeeCheckInCheckOutRequest) GetCheckOutTimestamp() string {
	if x != nil {
		return x.CheckOutTimestamp
	}
	return ""
}

func (x *EmployeeCheckInCheckOutRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type EmployeeCheckInCheckOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeCheckInCheckOutResponse) Reset() {
	*x = EmployeeCheckInCheckOutResponse{}
	mi := &file_proto_monitor_type_update_employee_attendance_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeCheckInCheckOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeCheckInCheckOutResponse) ProtoMessage() {}

func (x *EmployeeCheckInCheckOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_type_update_employee_attendance_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeCheckInCheckOutResponse.ProtoReflect.Descriptor instead.
func (*EmployeeCheckInCheckOutResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_type_update_employee_attendance_status_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeCheckInCheckOutResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *EmployeeCheckInCheckOutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_monitor_type_update_employee_attendance_status_proto protoreflect.FileDescriptor

const file_proto_monitor_type_update_employee_attendance_status_proto_rawDesc = "" +
	"\n" +
	":proto/monitor/type/update_employee_attendance_status.proto\x12\amonitor\"\xb4\x02\n" +
	"\x1eEmployeeCheckInCheckOutRequest\x12\x10\n" +
	"\x03day\x18\x01 \x01(\x05R\x03day\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x1e\n" +
	"\n" +
	"employeeId\x18\x04 \x01(\tR\n" +
	"employeeId\x12 \n" +
	"\visCheckedIn\x18\x05 \x01(\bR\visCheckedIn\x12*\n" +
	"\x10checkInTimestamp\x18\x06 \x01(\tR\x10checkInTimestamp\x12\"\n" +
	"\fisCheckedOut\x18\a \x01(\bR\fisCheckedOut\x12,\n" +
	"\x11checkOutTimestamp\x18\b \x01(\tR\x11checkOutTimestamp\x12\x16\n" +
	"\x06domain\x18\t \x01(\tR\x06domain\"S\n" +
	"\x1fEmployeeCheckInCheckOutResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x12Z\x10genproto/monitorb\x06proto3"

var (
	file_proto_monitor_type_update_employee_attendance_status_proto_rawDescOnce sync.Once
	file_proto_monitor_type_update_employee_attendance_status_proto_rawDescData []byte
)

func file_proto_monitor_type_update_employee_attendance_status_proto_rawDescGZIP() []byte {
	file_proto_monitor_type_update_employee_attendance_status_proto_rawDescOnce.Do(func() {
		file_proto_monitor_type_update_employee_attendance_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_monitor_type_update_employee_attendance_status_proto_rawDesc), len(file_proto_monitor_type_update_employee_attendance_status_proto_rawDesc)))
	})
	return file_proto_monitor_type_update_employee_attendance_status_proto_rawDescData
}

var file_proto_monitor_type_update_employee_attendance_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_monitor_type_update_employee_attendance_status_proto_goTypes = []any{
	(*EmployeeCheckInCheckOutRequest)(nil),  // 0: monitor.EmployeeCheckInCheckOutRequest
	(*EmployeeCheckInCheckOutResponse)(nil), // 1: monitor.EmployeeCheckInCheckOutResponse
}
var file_proto_monitor_type_update_employee_attendance_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_monitor_type_update_employee_attendance_status_proto_init() }
func file_proto_monitor_type_update_employee_attendance_status_proto_init() {
	if File_proto_monitor_type_update_employee_attendance_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_monitor_type_update_employee_attendance_status_proto_rawDesc), len(file_proto_monitor_type_update_employee_attendance_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_monitor_type_update_employee_attendance_status_proto_goTypes,
		DependencyIndexes: file_proto_monitor_type_update_employee_attendance_status_proto_depIdxs,
		MessageInfos:      file_proto_monitor_type_update_employee_attendance_status_proto_msgTypes,
	}.Build()
	File_proto_monitor_type_update_employee_attendance_status_proto = out.File
	file_proto_monitor_type_update_employee_attendance_status_proto_goTypes = nil
	file_proto_monitor_type_update_employee_attendance_status_proto_depIdxs = nil
}
